# path definitions
output: /home/sergio814/Documents/PhD/code/logs/lxmert/snap/vqa
path_vqa_data: /home/sergio814/Documents/PhD/code/data/lxmert/data/introspect_noeq
path_image_features: /home/sergio814/Documents/PhD/code/data/lxmert/data/mscoco_imgfeat
load_lxmert_qa: /home/sergio814/Documents/PhD/code/data/lxmert/snap/pretrained/model

# what to train on
train: train
valid: val
pairs: True
tiny: True
cnst_fcn: fcn3
gain: 0.75
start_loss_from_epoch: 0

# model properties
llayers: 9
xlayers: 5
rlayers: 5

# training hyperparameters
batch_size: 12 # hast to be 1/2 of normal batch because pairs = True
optim: bert
lr: 0.00005
epochs: 4
tqdm: True
